DATABRICKS_CLUSTER_ID="0721-132926-7xmg1s5j"
DATABRICKS_TOKEN="dapi9d2425f191ced4829a69eb941463fe0c-2"
DATABRICKS_HOST="https://adb-360063509637705.5.azuredatabricks.net"
DATABRICKS_HTTP_PATH = "/sql/1.0/warehouses/b275cf0c491fe3e0"
[openai]
api_key = "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"
